development:
  - accounts.larcity.ngrok.dev
test:
  - accounts.larcity.ngrok.test
  - accounts.larcity.test
  - www.example.com
staging:
  - accounts.staging.larcity.org
  - accounts.staging.larcity.tech
  - accounts.staging.larcity.business
  - accounts.larcity.dev
  - uches-m4-home-mini
  - uches-m4-home-mini.tail83bfcb.ts.net
  - accounts.staging.larcity.hopto.org
  #- accounts.staging.madebylar.city
  #- accounts.staging.larcity.com
production:
  - cami-production.onrender.com
  - accounts.larcity.hopto.org
  #- accounts.ho.lar.city
  #- accounts.ho.madebylar.city
  - accounts.ho.larcity.business
  #- accounts.larcity.com
  - accounts.larcity.tech
  #- accounts.lar.city
  #- www.larcity.com
  #- www.lar.city
  #- larcity.com
  #- lar.city
